# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'Tasha', :path => '../Tasha'

  target 'ExampleTests' do
    inherit! :search_paths
    use_frameworks!
      pod 'Quick'
      pod 'Nimble', '~> 7.0.2'
  end

end
